[2021-04-25 10:45:30,311] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 10:45:53,464] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 10:45:56,908] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 10:45:57,367] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 10:47:56,758] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 10:48:18,513] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 10:48:21,962] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 10:48:22,473] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 10:59:40,772] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 10:59:54,242] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 10:59:57,651] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 10:59:58,026] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 11:04:56,622] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 11:05:07,943] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 11:05:11,017] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 11:05:11,084] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 11:05:45,665] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素//span[text()="新增"]不可见,定位失败
[2021-04-25 11:06:29,145] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 11:06:40,645] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 11:06:43,855] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 11:06:44,094] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 11:12:04,131] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 11:12:23,991] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 11:12:27,036] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 11:12:27,889] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 11:15:49,555] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 11:16:00,862] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 11:16:04,168] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 11:16:04,448] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 11:25:32,794] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 11:25:55,911] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 11:25:59,279] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 11:25:59,879] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 11:31:25,006] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 11:32:14,133] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 11:32:17,761] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 11:32:18,787] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 11:37:07,686] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 11:37:21,043] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 11:37:24,403] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 11:37:24,828] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 11:37:35,789] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 11:37:48,259] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 11:37:51,378] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 11:46:54,613] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 11:48:07,903] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 11:48:57,575] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 11:49:01,012] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 11:49:01,950] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 14:05:27,679] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 14:06:14,298] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 14:06:17,635] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 14:06:18,588] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 14:11:09,565] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 14:11:54,647] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 14:11:57,833] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 14:11:58,691] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 14:17:06,692] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 14:17:53,030] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 14:17:56,334] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 14:17:57,226] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 14:20:07,353] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 14:20:55,334] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 14:20:58,570] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 14:20:59,501] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 14:36:26,541] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 14:37:13,619] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 14:37:16,952] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 14:37:17,890] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 14:40:22,081] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 14:41:07,936] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 14:41:11,035] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 14:41:11,848] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 14:45:27,208] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 14:46:14,108] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 14:46:17,258] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 14:46:18,115] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 14:48:29,188] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 14:49:16,380] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 14:49:19,652] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 14:49:20,563] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 14:50:44,166] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 14:51:09,194] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 14:51:12,255] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 14:51:12,893] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 14:53:51,905] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 14:54:16,039] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 14:54:19,387] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 14:54:19,885] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 15:35:36,129] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 15:36:05,962] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 15:36:09,525] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 15:36:10,481] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 15:40:21,888] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 15:40:45,006] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 15:40:48,538] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 15:40:49,095] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 18:43:45,497] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 18:43:50,330] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 18:43:53,929] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 18:43:57,211] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 18:43:58,546] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 工序检查 页面
[2021-04-25 18:44:03,450] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 18:44:10,393] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 18:44:12,281] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 18:44:13,992] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 18:44:18,266] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 工序检查 页面
[2021-04-25 18:44:23,520] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 18:44:27,131] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 工序检查 数据查看
[2021-04-25 18:44:32,905] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 18:44:37,805] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 18:44:40,843] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 18:44:49,721] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 18:44:49,895] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 18:44:56,159] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 18:44:56,162] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 18:45:06,058] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 18:45:06,727] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 18:45:09,083] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 18:45:09,226] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 工序检查 页面
[2021-04-25 18:45:09,995] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 18:45:10,751] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 工序检查 页面
[2021-04-25 18:45:14,399] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 18:45:17,905] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 18:45:18,584] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 工序检查 页面
[2021-04-25 18:45:20,499] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 工序检查 数据查看
[2021-04-25 18:45:20,524] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 18:45:22,619] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 工序检查 数据查看
[2021-04-25 18:45:24,210] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 18:45:25,924] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 工序检查 页面
[2021-04-25 18:45:32,747] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 工序检查 数据查看
[2021-04-25 18:45:36,438] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素//div[text()="监理抽检"]不可见,定位失败
[2021-04-25 18:45:37,884] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素//div[text()="监理抽检"]不可见,定位失败
[2021-04-25 18:45:39,972] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 工序检查 数据查看
[2021-04-25 18:45:43,696] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素//div[text()="监理抽检"]不可见,定位失败
[2021-04-25 18:45:47,505] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 返回到首页
[2021-04-25 18:45:48,185] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 返回到首页
[2021-04-25 18:45:51,802] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素//div[text()="监理抽检"]不可见,定位失败
[2021-04-25 18:45:54,003] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 返回到首页
[2021-04-25 18:46:02,455] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 返回到首页
[2021-04-25 19:00:29,641] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:00:32,895] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:00:45,420] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:00:51,122] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:01:00,931] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 19:01:03,836] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:01:04,481] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 19:01:08,344] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:01:08,669] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:10:06,138] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:10:11,137] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 19:10:14,351] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 19:10:14,416] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 工序检查 页面
[2021-04-25 19:10:19,252] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 工序检查 数据查看
[2021-04-25 19:10:30,598] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素//div[text()="监理抽检"]不可见,定位失败
[2021-04-25 19:10:38,896] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 返回到首页
[2021-04-25 19:25:39,863] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:25:44,816] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 19:25:48,326] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 19:25:48,392] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 工序检查 页面
[2021-04-25 19:25:55,014] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 工序检查 数据查看
[2021-04-25 19:26:04,011] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素//div[text()="监理抽检"]不可见,定位失败
[2021-04-25 19:26:12,268] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 返回到首页
[2021-04-25 19:26:54,737] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:33:56,979] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:34:10,405] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 19:34:13,716] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 19:34:14,140] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 工序检查 页面
[2021-04-25 19:34:21,059] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 工序检查 数据查看
[2021-04-25 19:34:33,171] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素//div[text()="监理抽检"]不可见,定位失败
[2021-04-25 19:56:43,915] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 19:57:08,914] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 19:57:12,597] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 19:57:13,544] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 20:00:55,075] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 20:01:22,072] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 20:01:25,437] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 20:01:26,407] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 进入到 现场收方单 页面
[2021-04-25 20:05:33,991] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 20:05:33,993] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 20:06:25,997] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 20:06:26,525] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 系统登录成功
[2021-04-25 20:06:30,881] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 20:06:32,715] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素layui-layer-btn1不可见,定位失败
[2021-04-25 20:06:43,865] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素home不可见,定位失败
[2021-04-25 20:06:45,737] - PublickLib.py[line:217] - fuc:__console- ERROR: >>> 元素home不可见,定位失败
[2021-04-25 20:08:40,062] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
[2021-04-25 20:08:40,505] - PublickLib.py[line:211] - fuc:__console- INFO: >>> 登录系统
